// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: c1/connector/v2/annotation_grant.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GrantMetadata with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GrantMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantMetadata with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GrantMetadataMultiError, or
// nil if none found.
func (m *GrantMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GrantMetadataValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GrantMetadataValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GrantMetadataValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GrantMetadataMultiError(errors)
	}

	return nil
}

// GrantMetadataMultiError is an error wrapping multiple validation errors
// returned by GrantMetadata.ValidateAll() if the designated constraints
// aren't met.
type GrantMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantMetadataMultiError) AllErrors() []error { return m }

// GrantMetadataValidationError is the validation error returned by
// GrantMetadata.Validate if the designated constraints aren't met.
type GrantMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantMetadataValidationError) ErrorName() string { return "GrantMetadataValidationError" }

// Error satisfies the builtin error interface
func (e GrantMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantMetadataValidationError{}

// Validate checks the field values on GrantExpandable with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GrantExpandable) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantExpandable with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantExpandableMultiError, or nil if none found.
func (m *GrantExpandable) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantExpandable) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Shallow

	if len(errors) > 0 {
		return GrantExpandableMultiError(errors)
	}

	return nil
}

// GrantExpandableMultiError is an error wrapping multiple validation errors
// returned by GrantExpandable.ValidateAll() if the designated constraints
// aren't met.
type GrantExpandableMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantExpandableMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantExpandableMultiError) AllErrors() []error { return m }

// GrantExpandableValidationError is the validation error returned by
// GrantExpandable.Validate if the designated constraints aren't met.
type GrantExpandableValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantExpandableValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantExpandableValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantExpandableValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantExpandableValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantExpandableValidationError) ErrorName() string { return "GrantExpandableValidationError" }

// Error satisfies the builtin error interface
func (e GrantExpandableValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantExpandable.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantExpandableValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantExpandableValidationError{}

// Validate checks the field values on GrantImmutable with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GrantImmutable) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantImmutable with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GrantImmutableMultiError,
// or nil if none found.
func (m *GrantImmutable) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantImmutable) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SourceId

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GrantImmutableValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GrantImmutableValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GrantImmutableValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GrantImmutableMultiError(errors)
	}

	return nil
}

// GrantImmutableMultiError is an error wrapping multiple validation errors
// returned by GrantImmutable.ValidateAll() if the designated constraints
// aren't met.
type GrantImmutableMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantImmutableMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantImmutableMultiError) AllErrors() []error { return m }

// GrantImmutableValidationError is the validation error returned by
// GrantImmutable.Validate if the designated constraints aren't met.
type GrantImmutableValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantImmutableValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantImmutableValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantImmutableValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantImmutableValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantImmutableValidationError) ErrorName() string { return "GrantImmutableValidationError" }

// Error satisfies the builtin error interface
func (e GrantImmutableValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantImmutable.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantImmutableValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantImmutableValidationError{}

// Validate checks the field values on GrantAlreadyExists with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrantAlreadyExists) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantAlreadyExists with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantAlreadyExistsMultiError, or nil if none found.
func (m *GrantAlreadyExists) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantAlreadyExists) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GrantAlreadyExistsMultiError(errors)
	}

	return nil
}

// GrantAlreadyExistsMultiError is an error wrapping multiple validation errors
// returned by GrantAlreadyExists.ValidateAll() if the designated constraints
// aren't met.
type GrantAlreadyExistsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantAlreadyExistsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantAlreadyExistsMultiError) AllErrors() []error { return m }

// GrantAlreadyExistsValidationError is the validation error returned by
// GrantAlreadyExists.Validate if the designated constraints aren't met.
type GrantAlreadyExistsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantAlreadyExistsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantAlreadyExistsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantAlreadyExistsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantAlreadyExistsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantAlreadyExistsValidationError) ErrorName() string {
	return "GrantAlreadyExistsValidationError"
}

// Error satisfies the builtin error interface
func (e GrantAlreadyExistsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantAlreadyExists.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantAlreadyExistsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantAlreadyExistsValidationError{}

// Validate checks the field values on GrantAlreadyRevoked with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrantAlreadyRevoked) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantAlreadyRevoked with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantAlreadyRevokedMultiError, or nil if none found.
func (m *GrantAlreadyRevoked) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantAlreadyRevoked) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GrantAlreadyRevokedMultiError(errors)
	}

	return nil
}

// GrantAlreadyRevokedMultiError is an error wrapping multiple validation
// errors returned by GrantAlreadyRevoked.ValidateAll() if the designated
// constraints aren't met.
type GrantAlreadyRevokedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantAlreadyRevokedMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantAlreadyRevokedMultiError) AllErrors() []error { return m }

// GrantAlreadyRevokedValidationError is the validation error returned by
// GrantAlreadyRevoked.Validate if the designated constraints aren't met.
type GrantAlreadyRevokedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantAlreadyRevokedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantAlreadyRevokedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantAlreadyRevokedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantAlreadyRevokedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantAlreadyRevokedValidationError) ErrorName() string {
	return "GrantAlreadyRevokedValidationError"
}

// Error satisfies the builtin error interface
func (e GrantAlreadyRevokedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantAlreadyRevoked.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantAlreadyRevokedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantAlreadyRevokedValidationError{}
