// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: c1/connector/v2/annotation_sync_id.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ActiveSync with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ActiveSync) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ActiveSync with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ActiveSyncMultiError, or
// nil if none found.
func (m *ActiveSync) ValidateAll() error {
	return m.validate(true)
}

func (m *ActiveSync) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return ActiveSyncMultiError(errors)
	}

	return nil
}

// ActiveSyncMultiError is an error wrapping multiple validation errors
// returned by ActiveSync.ValidateAll() if the designated constraints aren't met.
type ActiveSyncMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ActiveSyncMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ActiveSyncMultiError) AllErrors() []error { return m }

// ActiveSyncValidationError is the validation error returned by
// ActiveSync.Validate if the designated constraints aren't met.
type ActiveSyncValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ActiveSyncValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ActiveSyncValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ActiveSyncValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ActiveSyncValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ActiveSyncValidationError) ErrorName() string { return "ActiveSyncValidationError" }

// Error satisfies the builtin error interface
func (e ActiveSyncValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sActiveSync.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ActiveSyncValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ActiveSyncValidationError{}
